/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author LAB3M3
 */
public class Inicio_GUI extends javax.swing.JFrame {
String resultado="";


    
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CincoOuSete = new javax.swing.JButton();
        OitoOuNove = new javax.swing.JButton();
        ZeroOuTres = new javax.swing.JButton();
        SeisOuUm = new javax.swing.JButton();
        QuatroOuDois = new javax.swing.JButton();
        SAIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ENTRAR = new javax.swing.JButton();
        resul = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        CincoOuSete.setBackground(new java.awt.Color(51, 51, 255));
        CincoOuSete.setForeground(new java.awt.Color(255, 255, 255));
        CincoOuSete.setText("5 OU 7");
        CincoOuSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoOuSeteActionPerformed(evt);
            }
        });
        jPanel1.add(CincoOuSete);
        CincoOuSete.setBounds(390, 270, 260, 40);

        OitoOuNove.setBackground(new java.awt.Color(51, 51, 255));
        OitoOuNove.setForeground(new java.awt.Color(255, 255, 255));
        OitoOuNove.setText("8 OU 9");
        OitoOuNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OitoOuNoveActionPerformed(evt);
            }
        });
        jPanel1.add(OitoOuNove);
        OitoOuNove.setBounds(30, 270, 270, 40);

        ZeroOuTres.setBackground(new java.awt.Color(51, 51, 255));
        ZeroOuTres.setForeground(new java.awt.Color(255, 255, 255));
        ZeroOuTres.setText("0 OU 3");
        ZeroOuTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroOuTresActionPerformed(evt);
            }
        });
        jPanel1.add(ZeroOuTres);
        ZeroOuTres.setBounds(390, 340, 260, 40);

        SeisOuUm.setBackground(new java.awt.Color(51, 51, 255));
        SeisOuUm.setForeground(new java.awt.Color(255, 255, 255));
        SeisOuUm.setText("6 OU 1");
        SeisOuUm.setBorderPainted(false);
        SeisOuUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisOuUmActionPerformed(evt);
            }
        });
        jPanel1.add(SeisOuUm);
        SeisOuUm.setBounds(30, 340, 270, 40);

        QuatroOuDois.setBackground(new java.awt.Color(51, 51, 255));
        QuatroOuDois.setForeground(new java.awt.Color(255, 255, 255));
        QuatroOuDois.setText("4 OU 2");
        QuatroOuDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuatroOuDoisActionPerformed(evt);
            }
        });
        jPanel1.add(QuatroOuDois);
        QuatroOuDois.setBounds(390, 410, 260, 40);

        SAIR.setBackground(new java.awt.Color(51, 51, 255));
        SAIR.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SAIR.setForeground(new java.awt.Color(255, 255, 255));
        SAIR.setText("SAIR");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR);
        SAIR.setBounds(30, 415, 110, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECIONE OS 4 NÚMEROS DA SUA SENHA  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 120, 530, 30);

        ENTRAR.setBackground(new java.awt.Color(51, 51, 255));
        ENTRAR.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ENTRAR.setForeground(new java.awt.Color(255, 255, 255));
        ENTRAR.setText("ENTRAR");
        ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRARActionPerformed(evt);
            }
        });
        jPanel1.add(ENTRAR);
        ENTRAR.setBounds(200, 415, 100, 40);
        jPanel1.add(resul);
        resul.setBounds(190, 170, 290, 70);

        jPanel2.setBackground(new java.awt.Color(17, 53, 166));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logotipo.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 210, 50);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("|  O banco da inclusão");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 20, 330, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(672, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CincoOuSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoOuSeteActionPerformed
        String senha5 = "5";
        resultado+=senha5;
        resul.setText(String.valueOf(resultado));
      
       
    }//GEN-LAST:event_CincoOuSeteActionPerformed

    private void OitoOuNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OitoOuNoveActionPerformed
        String Senha9 = "9";
        resultado+=Senha9;
         resul.setText(String.valueOf(resultado));
         
    }//GEN-LAST:event_OitoOuNoveActionPerformed

    private void ZeroOuTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroOuTresActionPerformed
       String Senha3 = "3";
       resultado+=Senha3;
       resul.setText(String.valueOf(resultado));
        
    }//GEN-LAST:event_ZeroOuTresActionPerformed

    private void QuatroOuDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuatroOuDoisActionPerformed
      String Senha2 = "2";
      resultado+=Senha2;
      resul.setText(String.valueOf(resultado));
       
    }//GEN-LAST:event_QuatroOuDoisActionPerformed

    private void SeisOuUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisOuUmActionPerformed
        String Senha1 = "1";
        resultado+=Senha1;
        resul.setText(String.valueOf(resultado));
  
    }//GEN-LAST:event_SeisOuUmActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SAIRActionPerformed

    private void ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRARActionPerformed

        if(resultado.equals("9235")){
            new Tela02_GUI().setVisible(true);
            this.dispose();

        }
        else{
            JOptionPane.showMessageDialog(null,"SENHA INVÁLIDA !");
            resultado = "";
            resul.setText(String.valueOf(resultado));
            
        }
         this.dispose();

    }//GEN-LAST:event_ENTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CincoOuSete;
    private javax.swing.JButton ENTRAR;
    private javax.swing.JButton OitoOuNove;
    private javax.swing.JButton QuatroOuDois;
    private javax.swing.JButton SAIR;
    private javax.swing.JButton SeisOuUm;
    private javax.swing.JButton ZeroOuTres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField resul;
    // End of variables declaration//GEN-END:variables
}
