/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author LAB3M3
 */
public class Tela02_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Tela02_GUI
     */
    public Tela02_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pagamento = new javax.swing.JButton();
        depositos = new javax.swing.JButton();
        auxilio = new javax.swing.JButton();
        saque = new javax.swing.JButton();
        saldoExtratos = new javax.swing.JButton();
        transferencias = new javax.swing.JButton();
        SAIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 8, 126));
        jPanel1.setLayout(null);

        pagamento.setBackground(new java.awt.Color(204, 204, 204));
        pagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pagamento.setForeground(new java.awt.Color(255, 255, 255));
        pagamento.setText("PAGAMENTOS");
        pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(pagamento);
        pagamento.setBounds(30, 220, 280, 70);

        depositos.setBackground(new java.awt.Color(204, 204, 204));
        depositos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        depositos.setForeground(new java.awt.Color(255, 255, 255));
        depositos.setText("DEPÓSITOS");
        depositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositosActionPerformed(evt);
            }
        });
        jPanel1.add(depositos);
        depositos.setBounds(30, 120, 280, 70);

        auxilio.setBackground(new java.awt.Color(204, 204, 204));
        auxilio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        auxilio.setForeground(new java.awt.Color(255, 255, 255));
        auxilio.setText("AUXÍLIO EMERGENCIAL");
        auxilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxilioActionPerformed(evt);
            }
        });
        jPanel1.add(auxilio);
        auxilio.setBounds(440, 120, 280, 70);

        saque.setBackground(new java.awt.Color(204, 204, 204));
        saque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saque.setForeground(new java.awt.Color(255, 255, 255));
        saque.setText("SAQUE");
        saque.setBorderPainted(false);
        saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueActionPerformed(evt);
            }
        });
        jPanel1.add(saque);
        saque.setBounds(440, 320, 280, 70);

        saldoExtratos.setBackground(new java.awt.Color(204, 204, 204));
        saldoExtratos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saldoExtratos.setForeground(new java.awt.Color(255, 255, 255));
        saldoExtratos.setText("SALDO E EXTRATOS");
        saldoExtratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoExtratosActionPerformed(evt);
            }
        });
        jPanel1.add(saldoExtratos);
        saldoExtratos.setBounds(440, 220, 280, 70);

        transferencias.setBackground(new java.awt.Color(204, 204, 204));
        transferencias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        transferencias.setForeground(new java.awt.Color(255, 255, 255));
        transferencias.setText("TRANSFERÊNCIA");
        transferencias.setBorderPainted(false);
        transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciasActionPerformed(evt);
            }
        });
        jPanel1.add(transferencias);
        transferencias.setBounds(30, 320, 280, 70);

        SAIR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SAIR.setForeground(new java.awt.Color(51, 51, 255));
        SAIR.setText("VOLTAR");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR);
        SAIR.setBounds(30, 420, 690, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/autoatendimento.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -4, 750, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(749, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoActionPerformed
        JOptionPane.showMessageDialog(null, "Função inoperante no momento !");
        

    }//GEN-LAST:event_pagamentoActionPerformed

    private void depositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositosActionPerformed
     JOptionPane.showMessageDialog(null, "Função inoperante no momento !");
       
    }//GEN-LAST:event_depositosActionPerformed

    private void auxilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxilioActionPerformed
       JOptionPane.showMessageDialog(null, "Função inoperante no momento !");
       
    }//GEN-LAST:event_auxilioActionPerformed

    private void saqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueActionPerformed
         new Tela03_GUI().setVisible(true);
         this.dispose();   

    }//GEN-LAST:event_saqueActionPerformed

    private void saldoExtratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoExtratosActionPerformed
         JOptionPane.showMessageDialog(null, "Função inoperante no momento !");
         

    }//GEN-LAST:event_saldoExtratosActionPerformed

    private void transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciasActionPerformed
        JOptionPane.showMessageDialog(null, "Função inoperante no momento !");
        
    }//GEN-LAST:event_transferenciasActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        new Inicio_GUI().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_SAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela02_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela02_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela02_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela02_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela02_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAIR;
    private javax.swing.JButton auxilio;
    private javax.swing.JButton depositos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagamento;
    private javax.swing.JButton saldoExtratos;
    private javax.swing.JButton saque;
    private javax.swing.JButton transferencias;
    // End of variables declaration//GEN-END:variables

    void setVisable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
